<Project Sdk="Microsoft.NET.Sdk">

  <!-- Build Settings -->
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <!-- Project Identity -->
  <PropertyGroup>
    <AssemblyName>Genova.$(MSBuildProjectName)</AssemblyName>
    <RootNamespace>Genova.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
  </PropertyGroup>

  <!-- Versioning -->
  <PropertyGroup>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Version>1.0.0</Version>
  </PropertyGroup>

  <!-- Analyzers -->
  <PropertyGroup>
    <StyleCopAnalyzersSettingsFile>..\stylecop.json</StyleCopAnalyzersSettingsFile>
  </PropertyGroup>

  <!-- Test Metadata -->
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <TestResultsDirectory>$(SolutionDir)~TestResults</TestResultsDirectory>
  </PropertyGroup>

  <!-- Package References -->
  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="coverlet.msbuild" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="FluentAssertions" Version="8.6.0" />
    <PackageReference Include="Genova.Common" Version="1.0.0-20260602-0830" />
    <PackageReference Include="Genova.Testing" Version="1.0.0-20260602-1226" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="MSTest" Version="3.6.4" />
  </ItemGroup>

  <!-- Project References -->
  <ItemGroup>
    <ProjectReference Include="..\Theme\Theme.csproj" />
  </ItemGroup>

  <!-- Implicit Using -->
  <ItemGroup>
  </ItemGroup>

</Project>