<Project Sdk="Microsoft.NET.Sdk.Razor">

  <!-- Build Settings -->
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <!-- Project Identity -->
  <PropertyGroup>
    <AssemblyName>Genova.$(MSBuildProjectName)</AssemblyName>
    <RootNamespace>Genova.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
  </PropertyGroup>

  <!-- Versioning -->
  <PropertyGroup>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Version>1.0.0</Version>
  </PropertyGroup>

  <!-- Analyzers -->
  <PropertyGroup>
    <StyleCopAnalyzersSettingsFile>..\stylecop.json</StyleCopAnalyzersSettingsFile>
  </PropertyGroup>

  <!-- Documentation -->
  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <!-- Razor Compilation -->
  <PropertyGroup>
    <!-- Enable Razor compilation -->
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <RazorCompileOnBuild>true</RazorCompileOnBuild>
    <RazorCompileOnPublish>true</RazorCompileOnPublish>

    <!-- Optional: embed generated Razor C# source files -->
    <EmbedRazorGenerateSources>true</EmbedRazorGenerateSources>
    <PreserveCompilationContext>true</PreserveCompilationContext>
  </PropertyGroup>

  <!-- Package References -->
  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="coverlet.msbuild" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Genova.Common" Version="1.0.0-20260607-0526" />
    <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="11.0.100-preview.4.26230.115">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <!-- Additional files -->
  <ItemGroup>
    <AdditionalFiles Include="..\stylecop.json" />
  </ItemGroup>

  <!-- Test Visibility -->
  <ItemGroup>
    <InternalsVisibleTo Include="Genova.Theme.UnitTests" />
  </ItemGroup>

  <!-- Embedded Files -->
  <ItemGroup>
    <EmbeddedResource Include="wwwroot\**" />
  </ItemGroup>

</Project>
